### ISSUE TITLE
Filename is wrong in aws-vpc module

### ISSUE THREAD

**Issue by chandanshanbhag2002** [e2eSolutionArchitect/terraform#1]
e2esa-module-aws-vpc/varianles.tf

**Comment by TheSolutionArchitect** [comment]
Appreciate your finding @chandanshanbhag2002 . I have fixed it. If you are interested to join our technical community by contributing knowledge feel free to let us know.  https://raw.githubusercontent.com/e2eSolutionArchitect/terraform/main/providers/aws/modules/e2esa-module-aws-vpc/variables.tf
