### ISSUE TITLE
Template missing?

### ISSUE THREAD

**Issue by LostS77** [e2eSolutionArchitect/terraform#2]
Hey so I am learning TF slowly and your examples are amazing.  But noticed in /providers/aws/modules/e2esa-module-aws-ecs-service/main.tf have 

`template = file("./../modules/e2esa-module-aws-ecs-service/templates/app/json.tpl")`

But I am not seeing an example of this template anywhere.  Can you include that template?

**Comment by TheSolutionArchitect** [comment]
Thank you for identifying this. I have added the file. Please check. I didnt test the new template file yet. Will appreicate if you test and let us know if any issues. Also we will love to welcome your contribution to this e2eSolutionArchitect community. If interested please feel free to contribute , share your knowledge.
